job('First-Maven-Project-Via-DSL') {
    description("First Maven job generated by the DSL on ${new Date()} — GitHub Maven project")
    
    scm {
        git {
            remote {
                url('https://github.com/ramugaddam418/mvnproj.git')
            }
            branch('main') // or 'master'
        }
    }

    triggers {
        scm('H/5 * * * *') // check every 5 minutes
    }

    steps {
        maven {
            goals('clean package')
           // mavenInstallation('Maven 3.9.6') // name from Jenkins Maven configuration
        }
    }

    publishers {
        archiveArtifacts('target/*.jar')
    }
}
